# SPDX-License-Identifier: GPL-2.0+


obj­$(CONFIG_TARGET_AP135) += 955x.o
obj­$(CONFIG_TARGET_AP135)+= init-955x.o
obj­$(CONFIG_TARGET_AP135)+= serial.o
obj­$(CONFIG_TARGET_AP135)+= board955x.o
obj­$(CONFIG_TARGET_AP135)+= qca-eth-955x.o
obj­$(CONFIG_TARGET_AP135)+= rgmii-cal-955x.o
obj­$(CONFIG_TARGET_AP135)+= athrs17_phy.o
obj­$(CONFIG_TARGET_AP135) += ath-pci.o

